# name: Deployment
# on:
#   push:
#     branches:
#       - main
# jobs:
#   deployment:
#     name: Function Deployment
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - id: auth
#         uses: google-github-actions/auth@v0.4.0
#         with:
#           credentials_json: ${{ secrets.service_account_credentials }}
#       - id: deploy
#         uses: google-github-actions/deploy-cloud-functions@v0.6.0
#         with:
#           name: shop-api-function
#           runtime: ruby30
#           region: europe-west2
#           service_account_email: ${{ secrets.service_account_email }}
#           env_vars: "SHOP_API_BASE_URL=${{ secrets.SHOP_API_INTERNAL_LB_ENDPOINT }}"
